# Generated by Django 3.2.5 on 2021-07-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=10000)),
                ('bg_couleur_menu_element', models.CharField(max_length=8)),
                ('bg_couleur_sous_menu', models.CharField(max_length=8)),
                ('bg_couleur_application', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=8)),
                ('lien', models.TextField()),
                ('ordre', models.IntegerField()),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=8)),
                ('lien', models.TextField()),
                ('ordre', models.IntegerField()),
                ('menu_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.menu_element')),
            ],
        ),
        migrations.CreateModel(
            name='Block_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=8)),
                ('lien', models.TextField()),
                ('ordre', models.IntegerField()),
                ('sous_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.sous_menu')),
            ],
        ),
    ]
