# Generated by Django 3.2.5 on 2021-08-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sous_menu',
            name='scraping_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sous_menu',
            name='scraping_type',
            field=models.CharField(choices=[('youtube', 'youtube'), ('facebook', 'facebook'), ('instagram', 'instagram')], default='youtube', max_length=20),
        ),
    ]
